version: '3.8'

services:
  nav-web-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nav-web-site
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # 挂载数据目录以持久化数据
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    networks:
      - nav-network

networks:
  nav-network:
    driver: bridge
