'use client';

import { cn } from '@/lib/utils';

interface BootstrapIconProps {
  name: string;
  className?: string;
  size?: number;
}

export function BootstrapIcon({ name, className, size = 24 }: BootstrapIconProps) {
  return (
    <i 
      className={cn(`bi bi-${name}`, className)} 
      style={{ fontSize: `${size}px` }}
    />
  );
}

// 常用图标列表
export const BOOTSTRAP_ICONS = {
  // 学科类
  'book': '书籍',
  'book-half': '半开书',
  'books': '书本',
  'journal': '期刊',
  'journal-text': '文本期刊',
  'calculator': '计算器',
  'calculator-fill': '计算器填充',
  'translate': '翻译',
  'globe': '地球',
  'globe2': '地球2',
  'globe-americas': '美洲地球',
  'globe-asia-australia': '亚澳地球',
  'globe-europe-africa': '欧非地球',
  'clock-history': '历史',
  'clock': '时钟',
  'clock-fill': '时钟填充',
  'geo-alt': '地理',
  'geo-alt-fill': '地理填充',
  'geo': '地理位置',
  'heart-pulse': '生物',
  'heart-pulse-fill': '生物填充',
  'people': '政治',
  'people-fill': '政治填充',
  'person-workspace': '工作空间',
  'music-note': '音乐',
  'music-note-beamed': '音符',
  'music-note-list': '音乐列表',
  'palette': '艺术',
  'palette2': '调色板',
  'brush': '画笔',
  'brush-fill': '画笔填充',
  'paint-bucket': '油漆桶',

  // 娱乐类
  'controller': '游戏',
  'joystick': '手柄',
  'dice-1': '骰子1',
  'dice-2': '骰子2',
  'dice-3': '骰子3',
  'dice-4': '骰子4',
  'dice-5': '骰子5',
  'dice-6': '骰子6',
  'film': '电影',
  'camera': '摄影',
  'camera-fill': '摄影填充',
  'camera-reels': '摄像机',
  'camera-video': '视频摄像',
  'headphones': '音频',
  'headset': '耳机',
  'speaker': '扬声器',
  'tv': '电视',
  'tv-fill': '电视填充',
  'emoji-smile': '动漫',
  'emoji-laughing': '大笑',
  'emoji-heart-eyes': '爱心眼',
  'emoji-wink': '眨眼',
  'mask': '面具',

  // 生活类
  'house': '生活',
  'house-fill': '房屋填充',
  'house-door': '房门',
  'house-heart': '爱心房屋',
  'building': '建筑',
  'cup-hot': '饮食',
  'cup-straw': '吸管杯',
  'egg-fried': '煎蛋',
  'cake': '蛋糕',
  'cake2': '生日蛋糕',
  'bicycle': '运动',
  'scooter': '滑板车',
  'car-front': '交通',
  'car-front-fill': '汽车填充',
  'truck': '卡车',
  'bus-front': '公交车',
  'airplane': '飞机',
  'train-front': '火车',
  'bag-heart': '购物',
  'bag': '包',
  'bag-fill': '包填充',
  'basket': '篮子',
  'cart': '购物车',
  'calendar-event': '日程',
  'calendar': '日历',
  'calendar-date': '日期',
  'calendar-week': '周历',

  // 工具类
  'tools': '工具',
  'hammer': '锤子',
  'wrench': '扳手',
  'screwdriver': '螺丝刀',
  'gear': '设置',
  'gear-fill': '设置填充',
  'gears': '齿轮组',
  'search': '搜索',
  'search-heart': '搜索爱心',
  'download': '下载',
  'upload': '上传',
  'cloud-download': '云下载',
  'cloud-upload': '云上传',
  'share': '分享',
  'share-fill': '分享填充',
  'link': '链接',
  'link-45deg': '斜链接',
  'paperclip': '回形针',

  // 文档类
  'file-text': '文档',
  'file-text-fill': '文档填充',
  'file-code': '代码',
  'file-code-fill': '代码填充',
  'file-image': '图片',
  'file-image-fill': '图片填充',
  'file-music': '音乐文件',
  'file-music-fill': '音乐文件填充',
  'file-pdf': 'PDF',
  'file-pdf-fill': 'PDF填充',
  'file-word': 'Word文档',
  'file-excel': 'Excel文档',
  'file-ppt': 'PPT文档',
  'folder': '文件夹',
  'folder-fill': '文件夹填充',
  'folder-open': '打开文件夹',
  'archive': '归档',
  'archive-fill': '归档填充',

  // 通用类
  'star': '星星',
  'star-fill': '星星填充',
  'star-half': '半星',
  'heart': '心形',
  'heart-fill': '心形填充',
  'heart-arrow': '爱心箭头',
  'bookmark': '书签',
  'bookmark-fill': '书签填充',
  'bookmark-heart': '爱心书签',
  'flag': '旗帜',
  'flag-fill': '旗帜填充',
  'trophy': '奖杯',
  'trophy-fill': '奖杯填充',
  'award': '奖章',
  'award-fill': '奖章填充',
  'gift': '礼物',
  'gift-fill': '礼物填充',
  'balloon': '气球',
  'balloon-fill': '气球填充',
  'lightning': '闪电',
  'lightning-fill': '闪电填充',
  'fire': '火焰',
  'sun': '太阳',
  'sun-fill': '太阳填充',
  'moon': '月亮',
  'moon-fill': '月亮填充',
  'moon-stars': '月亮星星',
  'cloud': '云朵',
  'cloud-fill': '云朵填充',
  'cloud-rain': '雨云',
  'cloud-snow': '雪云',
  'umbrella': '雨伞',
  'umbrella-fill': '雨伞填充',
  'tree': '树木',
  'tree-fill': '树木填充',
  'flower1': '花朵',
  'flower2': '花朵2',
  'flower3': '花朵3',
  'gem': '宝石',
  'diamond': '钻石',
  'diamond-fill': '钻石填充',
  'shield': '盾牌',
  'shield-fill': '盾牌填充',
  'shield-check': '盾牌检查',
  'key': '钥匙',
  'key-fill': '钥匙填充',
  'lock': '锁',
  'lock-fill': '锁填充',
  'unlock': '解锁',
  'unlock-fill': '解锁填充',
  'eye': '眼睛',
  'eye-fill': '眼睛填充',
  'eye-slash': '隐藏',
  'hand-thumbs-up': '点赞',
  'hand-thumbs-up-fill': '点赞填充',
  'hand-thumbs-down': '点踩',
  'chat': '聊天',
  'chat-fill': '聊天填充',
  'chat-dots': '聊天点',
  'chat-heart': '聊天爱心',
  'envelope': '邮件',
  'envelope-fill': '邮件填充',
  'envelope-open': '打开邮件',
  'telephone': '电话',
  'telephone-fill': '电话填充',
  'phone': '手机',
  'phone-fill': '手机填充',
  'tablet': '平板',
  'tablet-fill': '平板填充',
  'laptop': '笔记本',
  'laptop-fill': '笔记本填充',
  'pc-display': '台式机',
  'pc-display-horizontal': '横屏显示器',
  'display': '显示器',
  'display-fill': '显示器填充',
  'keyboard': '键盘',
  'keyboard-fill': '键盘填充',
  'mouse': '鼠标',
  'mouse-fill': '鼠标填充',
  'mouse2': '鼠标2',
  'mouse3': '鼠标3',
  'printer': '打印机',
  'printer-fill': '打印机填充',
  'wifi': 'WiFi',
  'wifi-1': 'WiFi信号1',
  'wifi-2': 'WiFi信号2',
  'wifi-off': 'WiFi关闭',
  'bluetooth': '蓝牙',
  'battery': '电池',
  'battery-charging': '充电电池',
  'battery-full': '满电池',
  'battery-half': '半电池',
  'cpu': 'CPU',
  'cpu-fill': 'CPU填充',
  'memory': '内存',
  'hdd': '硬盘',
  'hdd-fill': '硬盘填充',
  'hdd-network': '网络硬盘',
  'hdd-rack': '硬盘架',
  'hdd-stack': '硬盘堆栈',
  'usb': 'USB',
  'usb-fill': 'USB填充',
  'usb-drive': 'USB驱动器',
  'usb-drive-fill': 'USB驱动器填充',

  // 社交媒体类
  'facebook': 'Facebook',
  'twitter': 'Twitter',
  'instagram': 'Instagram',
  'youtube': 'YouTube',
  'linkedin': 'LinkedIn',
  'github': 'GitHub',
  'discord': 'Discord',
  'telegram': 'Telegram',
  'whatsapp': 'WhatsApp',
  'wechat': '微信',
  'qq': 'QQ',
  'weibo': '微博',

  // 箭头和方向类
  'arrow-up': '向上箭头',
  'arrow-down': '向下箭头',
  'arrow-left': '向左箭头',
  'arrow-right': '向右箭头',
  'arrow-up-circle': '向上圆形箭头',
  'arrow-down-circle': '向下圆形箭头',
  'arrow-left-circle': '向左圆形箭头',
  'arrow-right-circle': '向右圆形箭头',
  'chevron-up': '向上尖括号',
  'chevron-down': '向下尖括号',
  'chevron-left': '向左尖括号',
  'chevron-right': '向右尖括号',

  // 状态和标记类
  'check': '检查',
  'check-circle': '检查圆形',
  'check-circle-fill': '检查圆形填充',
  'check-square': '检查方形',
  'check-square-fill': '检查方形填充',
  'x': '关闭',
  'x-circle': '关闭圆形',
  'x-circle-fill': '关闭圆形填充',
  'x-square': '关闭方形',
  'x-square-fill': '关闭方形填充',
  'plus': '加号',
  'plus-circle': '加号圆形',
  'plus-circle-fill': '加号圆形填充',
  'plus-square': '加号方形',
  'plus-square-fill': '加号方形填充',
  'dash': '减号',
  'dash-circle': '减号圆形',
  'dash-circle-fill': '减号圆形填充',
  'dash-square': '减号方形',
  'dash-square-fill': '减号方形填充',
  'exclamation': '感叹号',
  'exclamation-circle': '感叹号圆形',
  'exclamation-circle-fill': '感叹号圆形填充',
  'exclamation-triangle': '感叹号三角',
  'exclamation-triangle-fill': '感叹号三角填充',
  'question': '问号',
  'question-circle': '问号圆形',
  'question-circle-fill': '问号圆形填充',
  'info': '信息',
  'info-circle': '信息圆形',
  'info-circle-fill': '信息圆形填充',
  'info-square': '信息方形',
  'info-square-fill': '信息方形填充'
};

// 按类别分组的图标
export const ICON_CATEGORIES = {
  '学科': [
    'book', 'book-half', 'books', 'journal', 'journal-text',
    'calculator', 'calculator-fill', 'translate', 'globe', 'globe2',
    'clock-history', 'clock', 'geo-alt', 'geo-alt-fill', 'geo',
    'heart-pulse', 'heart-pulse-fill', 'people', 'people-fill',
    'music-note', 'music-note-beamed', 'music-note-list',
    'palette', 'palette2', 'brush', 'brush-fill', 'paint-bucket'
  ],
  '娱乐': [
    'controller', 'joystick', 'dice-1', 'dice-2', 'dice-3', 'dice-4', 'dice-5', 'dice-6',
    'film', 'camera', 'camera-fill', 'camera-reels', 'camera-video',
    'headphones', 'headset', 'speaker', 'tv', 'tv-fill',
    'emoji-smile', 'emoji-laughing', 'emoji-heart-eyes', 'emoji-wink', 'mask'
  ],
  '生活': [
    'house', 'house-fill', 'house-door', 'house-heart', 'building',
    'cup-hot', 'cup-straw', 'egg-fried', 'cake', 'cake2',
    'bicycle', 'scooter', 'car-front', 'car-front-fill', 'truck', 'bus-front',
    'airplane', 'train-front', 'bag-heart', 'bag', 'bag-fill', 'basket', 'cart',
    'calendar-event', 'calendar', 'calendar-date', 'calendar-week'
  ],
  '工具': [
    'tools', 'hammer', 'wrench', 'screwdriver', 'gear', 'gear-fill', 'gears',
    'search', 'search-heart', 'download', 'upload', 'cloud-download', 'cloud-upload',
    'share', 'share-fill', 'link', 'link-45deg', 'paperclip'
  ],
  '文档': [
    'file-text', 'file-text-fill', 'file-code', 'file-code-fill',
    'file-image', 'file-image-fill', 'file-music', 'file-music-fill',
    'file-pdf', 'file-pdf-fill', 'file-word', 'file-excel', 'file-ppt',
    'folder', 'folder-fill', 'folder-open', 'archive', 'archive-fill'
  ],
  '设备': [
    'phone', 'phone-fill', 'tablet', 'tablet-fill', 'laptop', 'laptop-fill',
    'pc-display', 'pc-display-horizontal', 'display', 'display-fill',
    'keyboard', 'keyboard-fill', 'mouse', 'mouse-fill', 'mouse2', 'mouse3',
    'printer', 'printer-fill', 'wifi', 'wifi-1', 'wifi-2', 'wifi-off',
    'bluetooth', 'battery', 'battery-charging', 'battery-full', 'battery-half',
    'cpu', 'cpu-fill', 'memory', 'hdd', 'hdd-fill', 'hdd-network',
    'usb', 'usb-fill', 'usb-drive', 'usb-drive-fill'
  ],
  '社交': [
    'facebook', 'twitter', 'instagram', 'youtube', 'linkedin', 'github',
    'discord', 'telegram', 'whatsapp', 'wechat', 'qq', 'weibo',
    'chat', 'chat-fill', 'chat-dots', 'chat-heart',
    'envelope', 'envelope-fill', 'envelope-open', 'telephone', 'telephone-fill'
  ],
  '状态': [
    'check', 'check-circle', 'check-circle-fill', 'check-square', 'check-square-fill',
    'x', 'x-circle', 'x-circle-fill', 'x-square', 'x-square-fill',
    'plus', 'plus-circle', 'plus-circle-fill', 'plus-square', 'plus-square-fill',
    'dash', 'dash-circle', 'dash-circle-fill', 'dash-square', 'dash-square-fill',
    'exclamation', 'exclamation-circle', 'exclamation-circle-fill',
    'exclamation-triangle', 'exclamation-triangle-fill',
    'question', 'question-circle', 'question-circle-fill',
    'info', 'info-circle', 'info-circle-fill', 'info-square', 'info-square-fill'
  ],
  '箭头': [
    'arrow-up', 'arrow-down', 'arrow-left', 'arrow-right',
    'arrow-up-circle', 'arrow-down-circle', 'arrow-left-circle', 'arrow-right-circle',
    'chevron-up', 'chevron-down', 'chevron-left', 'chevron-right'
  ],
  '通用': [
    'star', 'star-fill', 'star-half', 'heart', 'heart-fill', 'heart-arrow',
    'bookmark', 'bookmark-fill', 'bookmark-heart', 'flag', 'flag-fill',
    'trophy', 'trophy-fill', 'award', 'award-fill', 'gift', 'gift-fill',
    'balloon', 'balloon-fill', 'lightning', 'lightning-fill', 'fire',
    'sun', 'sun-fill', 'moon', 'moon-fill', 'moon-stars',
    'cloud', 'cloud-fill', 'cloud-rain', 'cloud-snow',
    'umbrella', 'umbrella-fill', 'tree', 'tree-fill',
    'flower1', 'flower2', 'flower3', 'gem', 'diamond', 'diamond-fill',
    'shield', 'shield-fill', 'shield-check', 'key', 'key-fill',
    'lock', 'lock-fill', 'unlock', 'unlock-fill',
    'eye', 'eye-fill', 'eye-slash', 'hand-thumbs-up', 'hand-thumbs-up-fill', 'hand-thumbs-down'
  ]
};
